/**
 * =============================================================================
 * CHAT IPC HANDLERS
 * =============================================================================
 *
 * Handles all chat-related IPC communication between renderer and main process.
 *
 * CHANNELS:
 * - chats:getAll       : Get all chats
 * - chats:get          : Get single chat by ID
 * - chats:create       : Create new chat
 * - chats:addMessage   : Add message to chat
 * - chats:updateMessage: Update existing message (for streaming)
 * - chats:sendMessage  : Send message to LLM and stream response
 * - chats:streamChunk  : (event) Broadcasts response chunks to renderer
 *
 * DATA FLOW FOR sendMessage:
 * ┌─────────────────────────────────────────────────────────────────────────┐
 * │  1. Frontend calls api.chats.sendMessage(chatId, content)               │
 * │                              │                                          │
 * │                              ▼                                          │
 * │  2. Handler marks chat as loading, calls chatService.generateResponse() │
 * │                              │                                          │
 * │                              ▼                                          │
 * │  3. Chat service streams from Gemini API                                │
 * │                              │                                          │
 * │                              ▼                                          │
 * │  4. Each chunk → webContents.send('chats:streamChunk', { chatId, chunk })│
 * │                              │                                          │
 * │                              ▼                                          │
 * │  5. Frontend receives chunks via api.chats.onStreamChunk() listener     │
 * │                              │                                          │
 * │                              ▼                                          │
 * │  6. Handler marks chat as not loading, returns success                  │
 * └─────────────────────────────────────────────────────────────────────────┘
 *
 * @module ipc/chats
 */

import { ipcMain, BrowserWindow } from 'electron'
import { dataStore } from '../services/dataStore'
import { chatService } from '../services/chatService'
import { IPC_CHANNELS, Chat, Message } from '../types'

/**
 * Registers all chat-related IPC handlers.
 */
export function registerChatHandlers(): void {
  // ---------------------------------------------------------------------------
  // READ Operations
  // ---------------------------------------------------------------------------

  /**
   * Get all chats.
   * Returns the complete chat list for display in sidebar/chat list.
   */
  ipcMain.handle(IPC_CHANNELS.CHATS_GET_ALL, () => {
    return dataStore.getChats()
  })

  /**
   * Get a single chat by ID.
   * Returns the chat with full message history.
   */
  ipcMain.handle(IPC_CHANNELS.CHATS_GET, (_event, id: string) => {
    return dataStore.getChatById(id)
  })

  // ---------------------------------------------------------------------------
  // WRITE Operations
  // ---------------------------------------------------------------------------

  /**
   * Create a new chat.
   *
   * @param chatData - Complete chat object (ID should be pre-generated by frontend)
   * @returns The created chat object
   */
  ipcMain.handle(IPC_CHANNELS.CHATS_CREATE, (_event, chatData: Chat) => {
    dataStore.createChat(chatData)
    return chatData
  })

  /**
   * Add a message to an existing chat.
   * Used for adding user messages and placeholder assistant messages.
   *
   * @param chatId - ID of the chat to add message to
   * @param message - Complete message object
   * @returns The added message
   */
  ipcMain.handle(
    IPC_CHANNELS.CHATS_ADD_MESSAGE,
    (_event, chatId: string, message: Message) => {
      dataStore.addMessage(chatId, message)
      return message
    }
  )

  /**
   * Update an existing message.
   * Primarily used for updating placeholder messages with streamed content.
   *
   * @param chatId - ID of the chat containing the message
   * @param messageId - ID of the message to update
   * @param updates - Partial message fields to update
   */
  ipcMain.handle(
    IPC_CHANNELS.CHATS_UPDATE_MESSAGE,
    (_event, chatId: string, messageId: string, updates: Partial<Message>) => {
      dataStore.updateMessage(chatId, messageId, updates)
      return { success: true }
    }
  )

  // ---------------------------------------------------------------------------
  // LLM Integration
  // ---------------------------------------------------------------------------

  /**
   * Send a message and generate an LLM response.
   *
   * This is the main handler for chat interactions:
   * 1. Retrieves the chat and marks it as loading
   * 2. Calls chatService to generate a streaming response
   * 3. Streams response chunks back to the renderer via 'chats:streamChunk' events
   * 4. Marks chat as not loading when complete
   *
   * @param chatId - ID of the chat to respond in
   * @param content - User message content that triggered this response
   * @returns Success status
   * @throws Error if chat not found or LLM generation fails
   */
  ipcMain.handle(
    IPC_CHANNELS.CHATS_SEND_MESSAGE,
    async (event, chatId: string, content: string) => {
      // Get the chat
      const chat = dataStore.getChatById(chatId)
      if (!chat) {
        throw new Error(`Chat ${chatId} not found`)
      }

      // NOTE: isLoadingResponse is managed by the frontend (useChat hook)
      // We don't update it here to avoid state sync conflicts
      // The frontend sets it before calling this, and clears it when this resolves

      // Get the sender's webContents for streaming responses back
      const webContents = event.sender
      const window = BrowserWindow.fromWebContents(webContents)

      // Generate streaming response
      await chatService.generateResponse(
        chat,
        content,
        // Chunk callback - sends each text chunk to the renderer
        (chunk: string) => {
          // Safety check: ensure window still exists
          if (window && !window.isDestroyed()) {
            webContents.send(IPC_CHANNELS.CHATS_STREAM_CHUNK, { chatId, chunk })
          }
        }
      )

      return { success: true }
    }
  )
}
